### ISSUE TITLE
React hooks Functional Components?

### ISSUE THREAD

**Issue by Amansg4** [mongodb-developer/mern-stack-example#11]
Was attempting to update the components of this into React Hooks functional components instead of class components, but I'm a little new and am kind of confusing myself. Any chance for a react hooks version?

#

**Comment by Danielg212** [comment]
Hi @Amansg4 
I just create https://github.com/mongodb-developer/mern-stack-example/pull/12 PR for it :)

**Comment by Pash10g** [comment]
It was done as part of PR #14 :)

Thank you for the efforts on this.
