### ISSUE TITLE
Mern Tutorial web page has an old record.js sample code

### ISSUE THREAD

**Issue by pat9579r** [mongodb-developer/mern-stack-example#17]
On the tutorial web page, the record.js offered uses person_name, person_group, person_level which do not map to the forms and cause display issues.

Also, the last line of the delete record uses:
response.status(obj); instead of response.json(obj) which prevents the recordList component from updating.

These will trip you up if you just try to "code along" and use the sample code from the tutorial web page.  Code found here in github has these changes and works as expected.

In some  cases "myFirstDatabase" is used, in others "employees" is used.  Probably best to create a single process.env.DATABASE in config.env for consistency.

**Comment by joellord** [comment]
Good catches! Thank you so much for letting us know, we will fix those as soon as possible.

**Comment by joellord** [comment]
The article has also been updated. Thank you for reporting those issues.
