### ISSUE TITLE
Several issues with details 

### ISSUE THREAD

**Issue by TangTang23333** [mongodb-developer/mern-stack-example#18]
1. names do not match, in server/routes/record.js,  within recordRoutes, names do not match names from client side, it should be   
let myobj = {
    person_name: req.body.name,
    person_position: req.body.position,
    person_level: req.body.level,
  }; 

2.  delete does not refresh the page with new records because it is not within a form.  A form should be added.

**Comment by joellord** [comment]
Thank you for reporting those, I will close this issue for now since those were also reported in #17
